### ISSUE TITLE
关于病毒整合的检测

### ISSUE THREAD

**Issue by the8thday** [Dangertrip/LiBis#7]
Hi YueYin,
最近在用LiBis对一批WGBS的数据进行分析，看到文档说LiBis支持检测病毒整合，但是文档中没有说明如何使用。
请问LIBis对BS数据检测病毒嵌合的具体用法是什么呢？
i wonder how to use LiBis to identify virus integration.

Thank you.

**Comment by Dangertrip** [comment]
Please contact me by email (dangertrip@hotmail.com)
